# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: allcentury
service: netflix-jobs

custom:
  bucket: ar-jobs

provider:
  name: aws
  runtime: ruby2.7
  memorySize: 128
  timeout: 20
  lambdaHashingVersion: 20201221
  region: us-west-2
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "s3:ListBucket"
          Resource: "arn:aws:s3:::${self:custom.bucket}"
        - Effect: "Allow"
          Action:
            - "s3:PutObject"
            - "s3:PutObjectAcl"
            - "s3:GetObject"
            - "s3:GetObjectAcl"
          Resource: "arn:aws:s3:::${self:custom.bucket}/*"
        - Effect: "Allow"
          Action:
            - "ses:SendEmail"
            - "ses:SendRawEmail"
          Resource: "*"

functions:
  get_jobs:
    handler: handler.get_jobs
    events:
      - schedule: rate(4 hours)
